(define (make-begin es) (if (pair? (cdr es)) (cons 'begin es) (car es)))
(define (not b) (if b #f #t))
(define cadr (lambda (x) (car (cdr x))))
(define caar (lambda (x) (car (car x))))
(define cdar (lambda (x) (cdr (car x))))
(define (map f xs)
  (if (pair? xs)
      (cons (f (car xs)) (map f (cdr xs)))
      '()))
(define list (lambda x x))
(define (append xs ys) (if (pair? xs) (cons (car xs) (append (cdr xs) ys)) ys))
(define (named-let->letrec fn bs es)
  (list 'letrec (list (list fn (list 'lambda (map car bs) (make-begin es))))
    (cons fn (map cadr bs))))
(define (let->lambda bs e)
  (cons
    (list 'lambda (map car bs) e)
    (map cadr bs)))
(defmacro (let bs . es)
  (if (symbol? bs)
      (named-let->letrec bs (car es) (cdr es))
      (let->lambda bs (make-begin es))))
(defmacro (letrec bs . es)
  (cons
    (list 'lambda (map car bs)
      (make-begin
        (append
          (map (lambda (e) (cons 'set! e)) bs)
          es)))
    (map (lambda _ 0) bs)))
(define (cond-clauses->ifs clauses)
  (if (pair? clauses)
      (let ((pred (caar clauses))
            (conseq (make-begin (cdar clauses)))
            (clauses (cdr clauses)))
        (if (eq? pred 'else)
            (if (pair? clauses)
                (error "cond-clauses->ifs" "misplaced else" clauses)
                conseq)
            (if (pair? clauses)
                (list 'if pred
                          conseq
                          (cond-clauses->ifs clauses))
                (list 'if pred conseq))))
      #f))
(defmacro (cond clause . clauses)
  (cond-clauses->ifs (cons clause clauses)))
(define values (lambda vs (call/cc (lambda (k) (apply k vs)))))
(define eof-object (let ((eof eof)) (lambda () eof)))
(define (fixnum-width) %fixnum-width)
(define (greatest-fixnum) %greatest-fixnum)
(define (least-fixnum) %least-fixnum)