(cons 1 '())
(+ 1 2)
'((lambda (x y) (+ (* x x) (* y y))) 3 4)
'(something)
((lambda x x) 1 2 3)
((lambda (x y) (+ x y)) 1 2)
(define sum-iter (lambda (n s) (if (<= n 0) s (sum-iter (- n 1) (+ s n)))))
(set! fib (lambda (n) (if (<= n 1) n (+ (fib (- n 1)) (fib (- n 2))))))
(fib 20)
(define list (lambda x x))
(begin
  (writeln (sum-iter 100 0))
  (writeln (sum-iter 1000 0))
  (writeln (sum-iter 10000 0)))
(if #t 'true 'false)
(if #f 'true 'false)
(define fact (lambda (n) (if (<= n 1) 1 (* n (fact (- n 1))))))
(fact 10)
(define (map f xs) (if (null? xs) '() (cons (f (car xs)) (map f (cdr xs)))))
(define (rep f n) (if (<= n 0) (f) (begin (f) (rep f (- n 1)))))
(rep (lambda _ (writeln 'yay!)) 10)
(map (lambda (x) (* x x)) '(2 3 4))
(define odd? (if #f #f))
(define even? (if #f #f))
(define (test)
  (define (odd? x) (if (<= x 0) #f (even? (- x 1))))
  (define (even? x) (if (<= x 0) #t (odd? (- x 1))))
  (writeln (odd? 3))
  (writeln (even? 3)))
(test)
(define (test) (eval '(set! test 'long-gone)))
(test)
test
even?
odd?
(apply + '(2 3))
(exit)