(set! writeln (lambda (x) (write x) (newline)))
(define even? (lambda (n) (if (<= n 0) #t (odd? (- n 1)))))
(define odd? (lambda (n) (if (<= n 0) #f (even? (- n 1)))))
(define (not b) (if b #f #t))
(define (and->ifs es)
  (if (pair? es)
      ((lambda x x) 'if (car es) (and->ifs (cdr es)) #f)
      #t))
(defmacro (and . es)
  (and->ifs es))
(writeln (and (even? 2) (not (odd? 2))))