(write (cons 1 #f))
(newline)
(write (pair? (cons 1 #f)))
(newline)
(write (car (cons 1 #f)))
(newline)
(write (cdr (cons 1 #f)))
(newline)
(write (cons 1 (cons 2 (cons 3 #f))))
(newline)
(write (cons 1 (cons 2 (cons 3 '()))))
(newline)