(write (procedure? procedure?)) (newline)
(write (symbol? 'symbol?)) (write (symbol? "symbol?")) (newline)
(write (symbol->string 'symbol->string)) (newline)
(write (string->symbol "string->symbol")) (newline)

(write (char? #\a)) (write (char? 10)) (newline)
(write (eq? (integer->char (char->integer #\a)) #\a)) (newline)
(write (eq? (char->integer (integer->char 10)) 10)) (newline)

(write (= 1 1))
(write (= 1 0))
(write (< 1 2))
(write (< 2 1))
(write (< 1 1))
(write (<= 1 2))
(write (<= 2 2))
(write (<= 3 2))
(write (> 2 1))
(write (> 1 2))
(write (> 2 2))
(write (>= 2 1))
(write (>= 2 2))
(write (>= 1 2))
(newline)

(write (eq? #b1011 (bitwise-ior #b1000 #b0011)))
(write (eq? #b1001 (bitwise-and #b1001 #b1111)))
(newline)

(write (eq? (mod 10 3) 1)) (newline)
(write (eq? (div 10 3) 3)) (newline)
(write (ash 1 3)) (newline)
(write (ash 8 -3)) (newline)
(write (eq? (ash (ash 8 3) -3) 8)) (newline)
