(write (integer? 0))
(newline)
(write (integer? #\a))
(newline)
(write (integer? #f))
(newline)

(write (boolean? 0))
(newline)
(write (boolean? #\a))
(newline)
(write (boolean? #f))
(newline)

(write (char? 0))
(newline)
(write (char? #\a))
(newline)
(write (char? #f))
(newline)

(write (char->integer #\B))
(newline)
(write (integer->char 66))
(newline)

(write (char->integer (integer->char 66)))
(newline)
(write (integer->char (char->integer #\B)))
(newline)