(write (string? ""))
(newline)
(write "compile-and-run")
(newline)
(write "\"\\\t\n\"")
(newline)
(let ((s "compile-and-run"))
    (string-set! s 0 #\C)
    (string-set! s (+ 2 1) #\P)
    (write s)
    (newline))
(write
  (string-length "compile-and-run"))
(newline)
(write
  (string-ref "abcd" 3))
(newline)
(let ((s (make-string 5 #\A)))
  (write (string? s))
  (newline)
  (write (string-length s))
  (newline)
  (write s)
  (newline)
  (string-set! s 0 #\r)
  (string-set! s 1 #\e)
  (string-set! s 2 #\i)
  (string-set! s 3 #\m)
  (string-set! s 4 #\u)
  (write s)
  (newline)
  (write (string-length s))
  (newline)
  (write (string? s))
  (newline)
  )