(write (not #t)) (newline)
(write (not #f)) (newline)
(write (and #t #t)) (newline)
(write (not (and #t #f))) (newline)
(write (not (and #f #t))) (newline)
(write (not (and #f #f))) (newline)
(write (or #t #t)) (newline)
(write (or #t #f)) (newline)
(write (or #f #t)) (newline)
(write (not (or #f #f))) (newline)