(let ((bv (make-bytevector 3 233)))
  (write bv) (newline)
  (write (bytevector? bv)) (newline)
  (write (bytevector-length bv)) (newline)
  (write (bytevector-u8-ref bv 0)) (newline)
  (write (bytevector-u8-ref bv 1)) (newline)
  (write (bytevector-u8-ref bv 2)) (newline)
  )

(let ((bv (make-bytevector 3)))
  (write (bytevector? bv)) (newline)
  (write (bytevector-length bv)) (newline)
  (bytevector-u8-set! bv 0 99)
  (bytevector-u8-set! bv 1 23)
  (bytevector-u8-set! bv 2 33)
  (write bv) (newline)
  (write (bytevector? bv)) (newline)
  (write (bytevector-u8-ref bv 0)) (newline)
  (write (bytevector-u8-ref bv 1)) (newline)
  (write (bytevector-u8-ref bv 2)) (newline)
  )

