(define (write-line x)
  (write x)
  (newline))

(define (length es)
  (if (pair? es)
      (+ 1 (length (cdr es)))
      0))

(define (f)
  (let recur ((i 0))
    (if (>= i 13)
        '()
        (cons i (recur (add1 i))))))

(let loop ((i 0) (len (length (f))))
  (if (< i 10000)
      (if (= len 13)
          (loop (add1 i) (length (f)))
          (write-line len))
      (write-line (f))))