(write-char #\h)
(write-char #\e)
(write-char #\l)
(write-char #\l)
(write-char #\o)
(write-char #\ )
(write-char #\w)
(write-char #\o)
(write-char #\r)
(write-char #\l)
(write-char #\d)
(newline)
(write #\A)
(newline)
(write 2)
(newline)
(write -1)
(newline)
; (write 438293613) error for bootstrapped compiler
(write 43829361)
(newline)
(write #t)
(newline)
(write #f)
(newline)
(write '())
(newline)