(set! add1 (lambda (x) (+ x 1)))
(set! sub1 (lambda (x) (- x 1)))
(set! list (lambda x x))
(load "preprocess/interp-preprocess.scm")
(load "preprocess/interp-kernel.scm")
(load "preprocess/lib/scheme-libs.scm")
(load "preprocess/lib/reader.scm")
(load "preprocess/lib/writer.scm")
(load "preprocess/lib/match-defmacro.scm")
(load "preprocess/lib/set.scm")
(load "preprocess/lib/utils.scm")
(load "preprocess/front.scm")
(load "preprocess/compiler.scm")
