(define (make-weak-ref k) (make-ephemeron k k))
(define (weak-ref r) (ephemeron-value r))
(define (weak-cons v w)
  (set! v (make-weak-ref v))
  (lambda (f) (f v w)))
(define (weak-car w)
  (w (lambda (x y) (weak-ref x))))
(define (weak-cdr w)
  (w (lambda (x y) y)))
(let ((w (let ((k (cons 2 3)))
          (make-weak-ref k))))
  (writeln (weak-ref w))
  (collect)
  (writeln (weak-ref w)))
(let ((v (cons 5 7)))
  (let ((e (let ((k (cons 2 3)))
            (weak-cons k v))))
    (writeln (weak-car e))
    (writeln (weak-cdr e))
    (collect)
    (writeln (weak-car e))
    (writeln (weak-cdr e))))
(let ((e #f))
  (let ((k (cons 1 2)))
    (let ((v (cons k #t)))
      (set! e (weak-cons k v)))
    (set! k #f))
  (collect)
  (writeln (weak-car e))
  (writeln (weak-cdr e)))