(let ()
  (define (writeln x) (write x) (newline))
  (define (prod xs)
    (call/cc (lambda (k)
      (let recur ((xs xs))
        (writeln xs)
        (cond
          ((null? xs) 1)
          ((not (pair? xs)) (k #f))
          ((eq? (car xs) 0) (k 0))
          (else (* (car xs) (recur (cdr xs)))))))))
  (writeln (prod '(1 2 3 4 5 6)))
  (writeln #f)
  (writeln (prod '(1 2 3 0 4 5 6)))
)