(let ()
  (define (writeln x) (write x) (newline))
  (define (prod xs)
    (call/cc (lambda (k)
      (let iter ((xs xs) (acm 1))
        (writeln xs)
        (cond
          ((null? xs) acm)
          ((not (pair? xs)) (k #f))
          ((eq? (car xs) 0) (k acm))
          (else (iter (cdr xs) (* (car xs) acm))))))))
  (writeln (prod '(1 2 3 4 5 6)))
  (writeln #f)
  (writeln (prod '(1 2 3 0 4 5 6)))
)