(let ((f (lambda () call/cc))
      (cwv (lambda () call-with-values)))
  ((cwv)
    (lambda ()
      ((f)
        (lambda (k)
         (k 0 1 2)
         (write #t)
         (newline))))
    (lambda x (write x)))
  (newline)
  )